[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nudimax"
version = "0.16.2"
dependencies = ['biopython>=1.81', 'pandas>=2.2.3']
requires-python = ">=3.8"
authors = [
  {name = "Richard Baker-Strader", email = "richardmsbs@gmail.com"},
  {name = "Lynn J. Bonomo", email = "lbonomo@calacademy.com"},
  {name = "Terrence Gosliner", email = "tgosliner@calacademy.com"},
  {name = "Paola Guzmán", email = "paola.guzman7@upr.edu"}
]
readme = "README.md"

[project.scripts]
nudimax = "nudimax:setup"